# Generated by Django 1.10 on 2016-08-11 20:30


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banning", "0003_auto_20150603_1149"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ban",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
