# Generated by Django 1.11.11 on 2018-04-01 14:52


from django.db import migrations, models

import autoslug.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=30)),
                ("name_en", models.CharField(max_length=30, null=True)),
                ("name_nl", models.CharField(max_length=30, null=True)),
                ("name_de", models.CharField(max_length=30, null=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from="name",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "slug_en",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from="name",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "slug_nl",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from="name",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "slug_de",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from="name",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="shop/thumbnails/",
                        verbose_name="thumbnail",
                    ),
                ),
            ],
            options={"verbose_name": "category", "verbose_name_plural": "categories",},
        ),
    ]
