# Generated by Django 4.2.19 on 2025-04-14 21:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import autoslug.fields
import ckeditor.fields
import taggit.managers


class Migration(migrations.Migration):

    replaces = [
        ("shop", "0001_initial"),
        ("shop", "0002_auto_20180401_1858"),
        ("shop", "0003_auto_20180401_2006"),
        ("shop", "0004_auto_20180419_2006"),
        ("shop", "0005_auto_20180422_1712"),
        ("shop", "0006_auto_20180422_1848"),
        ("shop", "0007_auto_20180930_1917"),
        ("shop", "0008_auto_20180930_1947"),
        ("shop", "0009_auto_20180930_2016"),
        ("shop", "0007_categorycarouselimage"),
        ("shop", "0010_merge_20181126_2144"),
        ("shop", "0011_homepagecategory_homepagecategorychild"),
        ("shop", "0012_product_image"),
        ("shop", "0013_auto_20181208_1230"),
        ("shop", "0014_auto_20181209_1930"),
        ("shop", "0015_auto_20181209_1936"),
        ("shop", "0016_auto_20181217_2121"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taggit", "0002_auto_20150616_2121"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(max_length=100, null=True, verbose_name="name"),
                ),
                (
                    "name_nl",
                    models.CharField(max_length=100, null=True, verbose_name="name"),
                ),
                (
                    "name_de",
                    models.CharField(max_length=100, null=True, verbose_name="name"),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from="name",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "slug_en",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from="name",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "slug_nl",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from="name",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "slug_de",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from="name",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="shop/category/", verbose_name="thumbnail"
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="enabled")),
                (
                    "seo_keyword",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="seo keyword",
                    ),
                ),
                (
                    "seo_keyword_de",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="seo keyword",
                    ),
                ),
                (
                    "seo_keyword_en",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="seo keyword",
                    ),
                ),
                (
                    "seo_keyword_nl",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="seo keyword",
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="ProductBrand",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="name")),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from="name",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        upload_to="images/product_brand_logos/",
                        verbose_name="logo",
                    ),
                ),
            ],
            options={
                "verbose_name": "product brand",
                "verbose_name_plural": "product brands",
            },
        ),
        migrations.CreateModel(
            name="ProductManufacturer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="manufacturer")),
            ],
            options={
                "verbose_name": "product manufacturer",
                "verbose_name_plural": "product manufacturers",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(max_length=200, null=True, verbose_name="name"),
                ),
                (
                    "name_nl",
                    models.CharField(max_length=200, null=True, verbose_name="name"),
                ),
                (
                    "name_de",
                    models.CharField(max_length=200, null=True, verbose_name="name"),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        max_length=200,
                        populate_from="name",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "slug_en",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        max_length=200,
                        null=True,
                        populate_from="name",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "slug_nl",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        max_length=200,
                        null=True,
                        populate_from="name",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "slug_de",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        max_length=200,
                        null=True,
                        populate_from="name",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=30, verbose_name="model name"),
                ),
                (
                    "model_name_en",
                    models.CharField(
                        max_length=30, null=True, verbose_name="model name"
                    ),
                ),
                (
                    "model_name_nl",
                    models.CharField(
                        max_length=30, null=True, verbose_name="model name"
                    ),
                ),
                (
                    "model_name_de",
                    models.CharField(
                        max_length=30, null=True, verbose_name="model name"
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        help_text="Number of items in stock", verbose_name="stock"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="price"
                    ),
                ),
                (
                    "vat",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=3, verbose_name="vat"
                    ),
                ),
                ("description", ckeditor.fields.RichTextField(blank=True)),
                (
                    "description_en",
                    ckeditor.fields.RichTextField(blank=True, null=True),
                ),
                (
                    "description_nl",
                    ckeditor.fields.RichTextField(blank=True, null=True),
                ),
                (
                    "description_de",
                    ckeditor.fields.RichTextField(blank=True, null=True),
                ),
                (
                    "seo_keyword",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="seo keyword",
                    ),
                ),
                (
                    "seo_keyword_en",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="seo keyword",
                    ),
                ),
                (
                    "seo_keyword_nl",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="seo keyword",
                    ),
                ),
                (
                    "seo_keyword_de",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="seo keyword",
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="length",
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="width"
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="height",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="weight",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shop.productbrand",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="shop.productmanufacturer",
                    ),
                ),
                (
                    "weight_unit",
                    models.CharField(
                        choices=[("g", "Gram"), ("kg", "Kilogram")],
                        default="g",
                        max_length=10,
                        verbose_name="weight unit",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="shop/product/",
                        verbose_name="image",
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="shop/product/", verbose_name="product image"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "product image",
                "verbose_name_plural": "product images",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="related_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="_product_related_products_+",
                to="shop.product",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(related_name="products", to="shop.category"),
        ),
        migrations.CreateModel(
            name="CategoryCarouselImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                (
                    "image",
                    models.ImageField(
                        upload_to="shop/category/",
                        verbose_name="category carousel image",
                    ),
                ),
                ("visible", models.BooleanField(default=True, verbose_name="visible")),
            ],
            options={
                "verbose_name": "category carousel image",
                "verbose_name_plural": "category carousel images",
            },
        ),
        migrations.CreateModel(
            name="HomepageCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Order in which to display category on the homepage",
                        verbose_name="order",
                    ),
                ),
                (
                    "main_category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homepage_categories",
                        to="shop.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "homepage category",
                "verbose_name_plural": "homepage categories",
            },
        ),
        migrations.CreateModel(
            name="HomepageCategoryChild",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Order in which to display category on the homepage",
                        verbose_name="order",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homepage_category_children",
                        to="shop.category",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="shop.homepagecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "homepage category child",
                "verbose_name_plural": "homepage category children",
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("paid", "Paid")],
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "cart",
                "verbose_name_plural": "carts",
            },
        ),
        migrations.CreateModel(
            name="CartProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(default=1, verbose_name="amount"),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_products",
                        to="shop.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_products",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "cart product",
                "verbose_name_plural": "cart products",
            },
        ),
        migrations.CreateModel(
            name="CustomerGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        verbose_name="discount",
                    ),
                ),
            ],
            options={
                "verbose_name": "customer group",
                "verbose_name_plural": "customer groups",
            },
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="rating",
                    ),
                ),
                ("submitted_on", models.DateTimeField(auto_now_add=True)),
                ("last_edited_on", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="shop.product",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "product review",
                "verbose_name_plural": "product reviews",
            },
        ),
    ]
