# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_auto_20180401_1858"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="enabled_de",
        ),
        migrations.RemoveField(
            model_name="category",
            name="enabled_en",
        ),
        migrations.RemoveField(
            model_name="category",
            name="enabled_nl",
        ),
    ]
