# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 18:06
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import autoslug.fields
import ckeditor.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0002_auto_20150616_2121"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0003_auto_20180401_2006"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(max_length=30, null=True, verbose_name="name"),
                ),
                (
                    "name_nl",
                    models.CharField(max_length=30, null=True, verbose_name="name"),
                ),
                (
                    "name_de",
                    models.CharField(max_length=30, null=True, verbose_name="name"),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from="name",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "slug_en",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from="name",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "slug_nl",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from="name",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "slug_de",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from="name",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=30, verbose_name="model name"),
                ),
                (
                    "model_name_en",
                    models.CharField(
                        max_length=30, null=True, verbose_name="model name"
                    ),
                ),
                (
                    "model_name_nl",
                    models.CharField(
                        max_length=30, null=True, verbose_name="model name"
                    ),
                ),
                (
                    "model_name_de",
                    models.CharField(
                        max_length=30, null=True, verbose_name="model name"
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        help_text="Number of items in stock", verbose_name="stock"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="price"
                    ),
                ),
                ("vat", models.IntegerField(default=0, verbose_name="vat")),
                ("description", ckeditor.fields.RichTextField(blank=True)),
                (
                    "description_en",
                    ckeditor.fields.RichTextField(blank=True, null=True),
                ),
                (
                    "description_nl",
                    ckeditor.fields.RichTextField(blank=True, null=True),
                ),
                (
                    "description_de",
                    ckeditor.fields.RichTextField(blank=True, null=True),
                ),
                (
                    "seo_keyword",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="seo keyword",
                    ),
                ),
                (
                    "seo_keyword_en",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="seo keyword",
                    ),
                ),
                (
                    "seo_keyword_nl",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="seo keyword",
                    ),
                ),
                (
                    "seo_keyword_de",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="seo keyword",
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="length",
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="width"
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="height",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="weight",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "verbose_name": "product",
                "verbose_name_plural": "products",
            },
        ),
        migrations.CreateModel(
            name="ProductBrand",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="name")),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from="name",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        upload_to="images/product_brand_logos/",
                        verbose_name="logo",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "verbose_name": "product brand",
                "verbose_name_plural": "product brands",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="shop/product/", verbose_name="product image"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="shop.Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "product image",
                "verbose_name_plural": "product images",
            },
        ),
        migrations.CreateModel(
            name="ProductManufacturer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="manufacturer")),
            ],
            options={
                "ordering": ["name"],
                "verbose_name": "product manufacturer",
                "verbose_name_plural": "product manufacturers",
            },
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", ckeditor.fields.RichTextField()),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="rating",
                    ),
                ),
                ("submitted_on", models.DateTimeField(auto_now_add=True)),
                ("last_edited_on", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="shop.Product",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "product review",
                "verbose_name_plural": "product reviews",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="shop.ProductBrand",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="shop.Category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="shop.ProductManufacturer",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="related_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="_product_related_products_+",
                to="shop.Product",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
