# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-23 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180422_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCarouselImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('image', models.ImageField(upload_to='shop/category/', verbose_name='category carousel image')),
                ('visible', models.BooleanField(default=True, verbose_name='visible')),
            ],
            options={
                'verbose_name': 'category carousel image',
                'verbose_name_plural': 'category carousel images',
            },
        ),
    ]
