# Generated by Django 1.11.15 on 2018-09-30 18:16


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_auto_20180930_1947"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_de",
            field=models.CharField(max_length=200, null=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_en",
            field=models.CharField(max_length=200, null=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_nl",
            field=models.CharField(max_length=200, null=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="seo_keyword",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="seo keyword"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="seo_keyword_de",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="seo keyword"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="seo_keyword_en",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="seo keyword"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="seo_keyword_nl",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="seo keyword"
            ),
        ),
    ]
