# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-26 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20180930_2016'),
        ('shop', '0007_categorycarouselimage'),
    ]

    operations = [
    ]
