# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-27 17:41
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_merge_20181126_2144"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomepageCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Order in which to display category on the homepage",
                        verbose_name="order",
                    ),
                ),
                (
                    "main_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homepage_categories",
                        to="shop.Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "homepage category",
                "verbose_name_plural": "homepage categories",
            },
        ),
        migrations.CreateModel(
            name="HomepageCategoryChild",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Order in which to display category on the homepage",
                        verbose_name="order",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homepage_category_children",
                        to="shop.Category",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="shop.HomepageCategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "homepage category child",
                "verbose_name_plural": "homepage category children",
            },
        ),
    ]
