# Generated by Django 1.11.15 on 2018-12-09 18:30


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_auto_20181208_1230"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productreview",
            name="text",
            field=models.TextField(),
        ),
    ]
