# Generated by Django 1.11.15 on 2018-12-09 18:36


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0014_auto_20181209_1930"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepagecategory",
            name="main_category",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homepage_categories",
                to="shop.Category",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="homepagecategorychild",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homepage_category_children",
                to="shop.Category",
            ),
        ),
    ]
