# Generated by Django 1.11.20 on 2019-05-24 07:15


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0017_auto_20190110_1938"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("ideal", "iDEAL"),
                            ("idealqr", "iDEAL QR"),
                            ("overboeking", "Bankoverboeking"),
                            ("ebill", "Ebill"),
                            ("bunq", "bunq"),
                            ("creditcard", "Creditcard"),
                            ("maestro", "Maestro"),
                            ("vpay", "V PAY"),
                            ("sofort", "SOFORT Banking"),
                            ("giropay", "Giropay"),
                            ("eps", "EPS"),
                            ("mistercash", "Bancontact"),
                            ("belfius", "Belfius Pay Button"),
                            ("homepay", "ING Home’Pay"),
                            ("kbc", "KBC"),
                            ("cbc", "CBC"),
                            ("paypalec", "PayPal Express Checkout"),
                            ("afterpay", "Afterpay"),
                            ("billink", "Billink achteraf betalen"),
                            ("capayable", "Capayable gespreid betalen"),
                            ("focum", "Focum AchterafBetalen"),
                            ("klarna", "Klarna Factuur"),
                            ("vvv", "VVV Giftcard"),
                            ("webshop", "Webshop Giftcard"),
                            ("paypal", "Paypal"),
                            ("bank_transfer", "Bank transfer"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="method",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        upload_to="shop/payment_methods/",
                        verbose_name="logo",
                    ),
                ),
                (
                    "enabeld",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the payment method can be used at checkout or not.",
                        verbose_name="enabled",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=1, verbose_name="order"),
                ),
            ],
            options={
                "verbose_name": "payment method",
                "verbose_name_plural": "payment methods",
            },
        ),
        migrations.CreateModel(
            name="ShopConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sisow_test_mode",
                    models.BooleanField(default=False, verbose_name="sisow test mode"),
                ),
                (
                    "sisow_merchant_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="sisow merchant ID"
                    ),
                ),
                (
                    "sisow_merchant_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="sisow merchant key"
                    ),
                ),
            ],
            options={
                "verbose_name": "Shop configuration",
            },
        ),
    ]
