# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 07:27
from __future__ import unicode_literals

from brouwers.shop.models.utils import get_max_order
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20190524_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='order',
            field=models.PositiveSmallIntegerField(
                default=get_max_order,
                verbose_name='order'
            ),
        ),
    ]
