# Generated by Django 2.0.13 on 2020-04-26 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0022_auto_20190629_1616"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
