# Generated by Django 3.2.12 on 2022-04-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0023_auto_20200426_1617"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="The exact payment data is provider-specific",
                verbose_name="payment data",
            ),
        ),
    ]
