# Generated by Django 3.2.13 on 2022-06-04 15:46

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0024_alter_payment_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="snapshot_data",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Snapshot of order information with frozen prices.",
                null=True,
                verbose_name="snapshot data",
            ),
        ),
    ]
