# Generated by Django 3.2.13 on 2022-06-19 12:46

from django.db import migrations, models

import brouwers.shop.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0026_address_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="order",
            field=models.PositiveSmallIntegerField(
                default=brouwers.shop.models.utils.get_max_order,
                verbose_name="ordering",
            ),
        ),
    ]
