# Generated by Django 3.2.13 on 2022-06-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0027_alter_paymentmethod_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="phone number"
            ),
        ),
    ]
