# Generated by Django 3.2.13 on 2022-07-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0028_alter_order_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopconfiguration",
            name="bank_transfer_instructions",
            field=models.TextField(
                default="",
                help_text="Enter the instructions to display to the customer on how to transfer the money.",
                verbose_name="instructions",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shopconfiguration",
            name="bank_transfer_instructions_de",
            field=models.TextField(
                help_text="Enter the instructions to display to the customer on how to transfer the money.",
                null=True,
                verbose_name="instructions",
            ),
        ),
        migrations.AddField(
            model_name="shopconfiguration",
            name="bank_transfer_instructions_en",
            field=models.TextField(
                help_text="Enter the instructions to display to the customer on how to transfer the money.",
                null=True,
                verbose_name="instructions",
            ),
        ),
        migrations.AddField(
            model_name="shopconfiguration",
            name="bank_transfer_instructions_nl",
            field=models.TextField(
                help_text="Enter the instructions to display to the customer on how to transfer the money.",
                null=True,
                verbose_name="instructions",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="method",
            field=models.CharField(
                choices=[
                    ("ideal", "iDEAL"),
                    ("sofort", "SOFORT Banking"),
                    ("mistercash", "Bancontact"),
                    ("paypal", "Paypal"),
                    ("bank_transfer", "Bank transfer"),
                ],
                max_length=50,
                unique=True,
                verbose_name="method",
            ),
        ),
    ]
