# Generated by Django 3.2.13 on 2022-07-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0029_auto_20220723_1510"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("payment_pending", "Payment pending"),
                    ("paid", "Paid"),
                ],
                default="open",
                max_length=50,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="method",
            field=models.CharField(max_length=50, unique=True, verbose_name="method"),
        ),
    ]
