# Generated by Django 3.2.16 on 2022-11-05 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0030_auto_20220723_1644"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductReview",
        ),
    ]
