# Generated by Django 3.2.16 on 2022-11-05 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0031_delete_productreview"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
        migrations.DeleteModel(
            name="ProductBrand",
        ),
    ]
