# Generated by Django 3.2.16 on 2022-12-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0032_auto_20221105_2111"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="seo_keyword",
        ),
        migrations.RemoveField(
            model_name="category",
            name="seo_keyword_de",
        ),
        migrations.RemoveField(
            model_name="category",
            name="seo_keyword_en",
        ),
        migrations.RemoveField(
            model_name="category",
            name="seo_keyword_nl",
        ),
        migrations.RemoveField(
            model_name="product",
            name="seo_keyword",
        ),
        migrations.RemoveField(
            model_name="product",
            name="seo_keyword_de",
        ),
        migrations.RemoveField(
            model_name="product",
            name="seo_keyword_en",
        ),
        migrations.RemoveField(
            model_name="product",
            name="seo_keyword_nl",
        ),
        migrations.AddField(
            model_name="category",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="If filled, populates the description meta tag for SEO purposes.",
                verbose_name="meta description",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="meta_description_de",
            field=models.TextField(
                blank=True,
                help_text="If filled, populates the description meta tag for SEO purposes.",
                null=True,
                verbose_name="meta description",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="meta_description_en",
            field=models.TextField(
                blank=True,
                help_text="If filled, populates the description meta tag for SEO purposes.",
                null=True,
                verbose_name="meta description",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="meta_description_nl",
            field=models.TextField(
                blank=True,
                help_text="If filled, populates the description meta tag for SEO purposes.",
                null=True,
                verbose_name="meta description",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="If filled, populates the description meta tag for SEO purposes. If left blank, then the HTML tags are stripped from the regular description field and this content is used.",
                verbose_name="meta description",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_description_de",
            field=models.TextField(
                blank=True,
                help_text="If filled, populates the description meta tag for SEO purposes. If left blank, then the HTML tags are stripped from the regular description field and this content is used.",
                null=True,
                verbose_name="meta description",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_description_en",
            field=models.TextField(
                blank=True,
                help_text="If filled, populates the description meta tag for SEO purposes. If left blank, then the HTML tags are stripped from the regular description field and this content is used.",
                null=True,
                verbose_name="meta description",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_description_nl",
            field=models.TextField(
                blank=True,
                help_text="If filled, populates the description meta tag for SEO purposes. If left blank, then the HTML tags are stripped from the regular description field and this content is used.",
                null=True,
                verbose_name="meta description",
            ),
        ),
    ]
