# Generated by Django 3.2.16 on 2022-12-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0033_auto_20221227_1158"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Inactive products do not show up on the site",
                verbose_name="active",
            ),
        ),
    ]
