# Generated by Django 3.2.16 on 2022-12-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0034_product_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=200, unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug_de",
            field=models.SlugField(
                max_length=200, null=True, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug_en",
            field=models.SlugField(
                max_length=200, null=True, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug_nl",
            field=models.SlugField(
                max_length=200, null=True, unique=True, verbose_name="slug"
            ),
        ),
    ]
