# Generated by Django 3.2.16 on 2022-12-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0035_auto_20221228_1159"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="length_unit",
            field=models.CharField(
                choices=[("mm", "Milimetre"), ("cm", "Centimetre"), ("m", "Metre")],
                default="cm",
                max_length=10,
                verbose_name="length unit",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="weight_unit",
            field=models.CharField(
                choices=[("g", "Gram"), ("kg", "Kilogram")],
                default="g",
                max_length=10,
                verbose_name="weight unit",
            ),
        ),
    ]
