# Generated by Django 3.2.16 on 2022-12-28 14:12

from django.db import migrations

import autoslug.fields


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0036_auto_20221228_1215"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=True, populate_from="name", unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug_de",
            field=autoslug.fields.AutoSlugField(
                editable=True,
                null=True,
                populate_from="name",
                unique=True,
                verbose_name="slug",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug_en",
            field=autoslug.fields.AutoSlugField(
                editable=True,
                null=True,
                populate_from="name",
                unique=True,
                verbose_name="slug",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug_nl",
            field=autoslug.fields.AutoSlugField(
                editable=True,
                null=True,
                populate_from="name",
                unique=True,
                verbose_name="slug",
            ),
        ),
    ]
