# Generated by Django 3.2.16 on 2022-12-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0037_auto_20221228_1512"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopconfiguration",
            name="paypal_client_id",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="paypal API client ID"
            ),
        ),
        migrations.AddField(
            model_name="shopconfiguration",
            name="paypal_sandbox",
            field=models.BooleanField(default=True, verbose_name="paypal sandbox"),
        ),
        migrations.AddField(
            model_name="shopconfiguration",
            name="paypal_secret",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="paypal API secret"
            ),
        ),
    ]
