# Generated by Django 3.2.16 on 2022-12-31 15:52

from django.db import migrations, models

import brouwers.shop.models.orders


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0039_auto_20221231_1651"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="reference",
            field=models.CharField(
                default=brouwers.shop.models.orders.get_order_reference,
                help_text="A unique order reference",
                max_length=16,
                unique=True,
                verbose_name="reference",
            ),
        ),
    ]
