# Generated by Django 3.2.16 on 2022-12-31 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0040_alter_order_reference"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="payment",
            name="order_or_historical_order",
        ),
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.OneToOneField(
                blank=True,
                help_text="The order being paid by this payment.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.order",
                verbose_name="order",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("historical_order__isnull", True), ("order__isnull", False)
                    ),
                    models.Q(
                        ("historical_order__isnull", False), ("order__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="order_or_historical_order",
            ),
        ),
    ]
