# Generated by Django 3.2.18 on 2023-05-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0041_auto_20221231_1709"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="language",
            field=models.CharField(
                choices=[("nl", "Dutch"), ("en", "English"), ("de", "German")],
                default="nl",
                max_length=10,
                verbose_name="language",
            ),
        ),
    ]
