# Generated by Django 3.2.19 on 2023-05-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0042_order_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopconfiguration",
            name="from_email",
            field=models.EmailField(
                blank=True,
                help_text="Email address for outgoing e-mails. This will end up in the 'From' header - you must ensure that your outgoing email server is appropriately configured. If left blank, the default value from the settings is used.",
                max_length=254,
                verbose_name="from email",
            ),
        ),
    ]
