# Generated by Django 4.2.10 on 2024-03-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0043_shopconfiguration_from_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="related_products",
            field=models.ManyToManyField(blank=True, to="shop.product"),
        ),
    ]
