# Generated by Django 4.2.11 on 2024-06-13 15:25

from django.db import migrations, models

import brouwers.general.fields


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0044_alter_product_related_products"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingCost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Descriptive label, e.g. 'enveloppe' or 'small package'.",
                        max_length=100,
                        verbose_name="label",
                    ),
                ),
                (
                    "country",
                    brouwers.general.fields.CountryField(
                        choices=[
                            ("N", "The Netherlands"),
                            ("B", "Belgium"),
                            ("D", "Germany"),
                        ],
                        help_text="Country to ship the order to.",
                        max_length=1,
                        verbose_name="country",
                    ),
                ),
                (
                    "max_weight",
                    models.PositiveSmallIntegerField(
                        help_text="Maximum weight (in grams) for orders to match this shipping cost.",
                        verbose_name="maximum weight",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Shipping cost for this weight limit, including VAT.",
                        max_digits=5,
                        verbose_name="price",
                    ),
                ),
            ],
            options={
                "verbose_name": "shipping cost",
                "verbose_name_plural": "shipping costs",
            },
        ),
        migrations.AddConstraint(
            model_name="shippingcost",
            constraint=models.UniqueConstraint(
                fields=("country", "max_weight"), name="unique_ranges"
            ),
        ),
    ]
