# Generated by Django 4.2.19 on 2025-04-06 15:40

import django.db.models.deletion
from django.db import migrations, models

import brouwers.general.fields


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0044_alter_product_related_products"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingCost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Descriptive label, e.g. 'enveloppe' or 'small package'.",
                        max_length=100,
                        verbose_name="label",
                    ),
                ),
                (
                    "country",
                    brouwers.general.fields.CountryField(
                        choices=[
                            ("N", "The Netherlands"),
                            ("B", "Belgium"),
                            ("D", "Germany"),
                        ],
                        help_text="Country to ship the order to.",
                        max_length=1,
                        verbose_name="country",
                    ),
                ),
                (
                    "max_weight",
                    models.PositiveSmallIntegerField(
                        help_text="Maximum weight (in grams) for orders to match this shipping cost.",
                        verbose_name="maximum weight",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Shipping cost for this weight limit, including VAT.",
                        max_digits=5,
                        verbose_name="price",
                    ),
                ),
            ],
            options={
                "verbose_name": "shipping cost",
                "verbose_name_plural": "shipping costs",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_method",
            field=models.CharField(
                choices=[("pickup", "Pickup"), ("mail", "By mail")],
                default="mail",
                max_length=20,
                verbose_name="delivery method",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_costs",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="shipping costs",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_address",
            field=models.OneToOneField(
                blank=True,
                help_text="Address for delivery",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="delivery_order",
                to="shop.address",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("delivery_address__isnull", False), ("delivery_method", "mail")
                    ),
                    models.Q(("delivery_method", "mail"), _negated=True),
                    _connector="OR",
                ),
                name="delivery_address_when_shipping",
                violation_error_message="A delivery address must be specified when deliverying via mail.",
            ),
        ),
        migrations.AddConstraint(
            model_name="shippingcost",
            constraint=models.UniqueConstraint(
                fields=("country", "max_weight"), name="unique_ranges"
            ),
        ),
    ]
