# Generated by Django 4.2.11 on 2024-06-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0045_shippingcost_shippingcost_unique_ranges"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_method",
            field=models.CharField(
                choices=[("pickup", "Pick up"), ("mail", "By mail")],
                default="mail",
                max_length=20,
                verbose_name="delivery method",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("delivery_address__isnull", False), ("delivery_method", "mail")
                ),
                name="delivery_address_when_shipping",
            ),
        ),
    ]
