# Generated by Django 4.2.19 on 2025-04-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "shop",
            "0017_auto_20190110_1938_squashed_0045_shippingcost_order_delivery_method_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopconfiguration",
            name="bank_transfer_instructions",
            field=models.TextField(
                help_text="Enter the instructions to display to the customer on how to transfer the money.",
                verbose_name="instructions",
            ),
        ),
    ]
