# Generated by Django 4.2.11 on 2024-06-13 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0046_order_delivery_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_address",
            field=models.OneToOneField(
                blank=True,
                help_text="Address for delivery",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="delivery_order",
                to="shop.address",
            ),
        ),
    ]
