# Generated by Django 5.2.13 on 2026-04-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0046_alter_homepagecategory_main_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="track_and_trace_code",
            field=models.CharField(
                blank=True,
                help_text="If available, the track and trace code for the client to follow their parcel.",
                max_length=100,
                verbose_name="track and trace code",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="track_and_trace_link",
            field=models.URLField(
                blank=True,
                help_text="If available, the clickable track and trace link for the client to follow their parcel. If both the link and code are provided, the link will be displayed in the email.",
                max_length=512,
                verbose_name="track and trace link",
            ),
        ),
    ]
