# Generated by Django 5.2.13 on 2026-04-26 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0047_order_track_and_trace_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Moment in time when the event occurred.",
                        verbose_name="timestamp",
                    ),
                ),
                ("event", models.CharField(max_length=50, verbose_name="event type")),
                (
                    "event_data",
                    models.JSONField(
                        blank=True,
                        help_text="Additional data relevant for the selected event type.",
                        null=True,
                        verbose_name="event data",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.order",
                        verbose_name="order",
                    ),
                ),
            ],
            options={
                "verbose_name": "order event",
                "verbose_name_plural": "order events",
            },
        ),
    ]
