# Generated by Django 4.2.11 on 2024-06-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0047_alter_order_delivery_address"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="order",
            name="delivery_address_when_shipping",
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_method",
            field=models.CharField(
                choices=[("pickup", "Pickup"), ("mail", "By mail")],
                max_length=20,
                verbose_name="delivery method",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("delivery_address__isnull", False), ("delivery_method", "mail")
                    ),
                    models.Q(("delivery_method", "mail"), _negated=True),
                    _connector="OR",
                ),
                name="delivery_address_when_shipping",
                violation_error_message="A delivery address must be specified when deliverying via mail.",
            ),
        ),
    ]
