# Generated by Django 4.2.19 on 2025-04-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0048_remove_order_delivery_address_when_shipping_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_costs",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="shipping costs",
            ),
        ),
    ]
