# Generated by Django 5.2.13 on 2026-05-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0048_orderevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopconfiguration",
            name="sendcloud_private_key",
            field=models.CharField(
                blank=True,
                help_text="Private key for the Sendcloud integration, also known as the 'api secret'.",
                verbose_name="sendcloud private key",
            ),
        ),
        migrations.AddField(
            model_name="shopconfiguration",
            name="sendcloud_public_key",
            field=models.CharField(
                blank=True,
                help_text="Public key for the Sendcloud integration, also known as the 'api key'.",
                verbose_name="sendcloud public key",
            ),
        ),
        migrations.AlterField(
            model_name="orderevent",
            name="event",
            field=models.CharField(
                choices=[
                    ("placed", "Order placed"),
                    ("status_changed", "Status changed"),
                    ("payment_status_changed", "Payment status changed"),
                    ("email_sent", "Email sent"),
                ],
                max_length=50,
                verbose_name="event type",
            ),
        ),
    ]
