# Generated by Django 5.2.13 on 2026-05-06 19:35

from django.db import migrations, models

import brouwers.general.fields


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0049_shopconfiguration_sendcloud_private_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SendcloudShippingOption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    brouwers.general.fields.CountryField(
                        choices=[
                            ("N", "The Netherlands"),
                            ("B", "Belgium"),
                            ("D", "Germany"),
                        ],
                        help_text="Country to ship the order to.",
                        max_length=1,
                        verbose_name="country",
                    ),
                ),
                (
                    "shipping_option_code",
                    models.CharField(
                        default="dpd:shop2home",
                        help_text="Shipping option to the specified country. Under the hood this stores the unique identifier from the Sendcloud API. Select a country and save this before you can pick a shipping option.",
                        max_length=100,
                        verbose_name="shipping option code",
                    ),
                ),
            ],
            options={
                "verbose_name": "sendcloud shipping option",
                "verbose_name_plural": "sendcloud shipping options",
                "constraints": [
                    models.UniqueConstraint(fields=("country",), name="unique_country")
                ],
            },
        ),
    ]
