# Generated by Django 5.2.13 on 2026-05-09 13:55

from django.db import migrations

import privates.fields
import privates.storages


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0050_sendcloudshippingoption"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_label",
            field=privates.fields.PrivateMediaFileField(
                blank=True,
                help_text="Shipping label (from Sendcloud) for the parcel.",
                storage=privates.storages.PrivateMediaFileSystemStorage(),
                upload_to="",
                verbose_name="shipping label",
            ),
        ),
    ]
