# Generated by Django 5.2.13 on 2026-05-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0051_order_shipping_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="sendcloud_shipment_id",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=200,
                verbose_name="sendcloud shipment ID",
            ),
        ),
    ]
