# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa', '0002_auto_20150405_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couple',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='couple',
            name='secret_santa',
        ),
        migrations.RemoveField(
            model_name='couple',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='secret_santa',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='user',
        ),
        migrations.DeleteModel(
            name='Couple',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='SecretSanta',
        ),
    ]
