language: python

dist: bionic

python:
  - "3.6"

cache:
  directories:
    - $HOME/.pip-cache

services:
  - postgresql
  - memcached
  # - redis-server
  # - elasticsearch

env:
  - DJANGO_SETTINGS_MODULE=brouwers.conf.travis

install:
  - pip install --upgrade setuptools pip
  - pip install -r requirements/ci.txt --cache-dir $HOME/.pip-cache
  - pip install coveralls codecov
  - npm install
  - npm run build

before_script:
  - src/manage.py collectstatic --noinput --link -v 0

script:
  - coverage run src/manage.py test src  -v 2

after_success:
  - coveralls
  - codecov
