version: "3.8"

services:
  django:
    command: python src/manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=1
    volumes:
      - ./src:/app/src
      - ./node_modules/:/app/node_modules/
