# Generated by Django 3.2.16 on 2023-01-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildphoto",
            name="image_gone",
            field=models.BooleanField(default=False, verbose_name="image gone"),
        ),
    ]
