# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 01:47
from __future__ import unicode_literals

import brouwers.kits.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0012_auto_20151206_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='kits',
            field=brouwers.kits.fields.KitsManyToManyField(blank=True, verbose_name='kits'),
        ),
    ]
