# Generated by Django 3.2.13 on 2022-04-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="public",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Can this album be viewed by everyone? Untick to make the album available only to yourself.",
                verbose_name="Public?",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="trash",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
