# Generated by Django 3.2.13 on 2022-06-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0002_auto_20220428_2022"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="order",
            field=models.PositiveSmallIntegerField(
                blank=True, db_index=True, default=1, null=True, verbose_name="ordering"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="order",
            field=models.PositiveSmallIntegerField(
                blank=True, default=1, null=True, verbose_name="ordering"
            ),
        ),
    ]
