# Generated by Django 3.2.16 on 2023-01-14 23:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("albums", "0003_auto_20220619_1446"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="votes",
        ),
        migrations.RemoveField(
            model_name="category",
            name="on_frontpage",
        ),
    ]
