# Generated by Django 4.2.19 on 2025-05-03 22:11

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0004_auto_20230115_0006"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="album",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.CombinedSearchVector(
                    django.contrib.postgres.search.SearchVector(
                        "title", config="dutch", weight="A"
                    ),
                    "||",
                    django.contrib.postgres.search.SearchVector(
                        "description", config="dutch", weight="C"
                    ),
                    django.contrib.postgres.search.SearchConfig("dutch"),
                ),
                name="album_search",
            ),
        ),
    ]
