# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='clean_title',
            field=models.CharField(blank=True, default=b'', max_length=256, verbose_name='album title'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(db_index=True, max_length=256, verbose_name='album title'),
        ),
    ]
