# Generated by Django 4.2.19 on 2025-04-14 21:27

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import autoslug.fields

import brouwers.forum_tools.fields


class Migration(migrations.Migration):
    replaces = [
        ("awards", "0001_initial"),
        ("awards", "0002_auto_20150405_2118"),
        ("awards", "0003_auto_20160811_2230"),
        ("awards", "0004_auto_20210420_2201"),
        ("awards", "0005_category_forum"),
        ("awards", "0006_project_topic"),
        ("awards", "0007_set_topic_id_from_url"),
        ("awards", "0008_auto_20210420_2307"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from="name",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "forum",
                    brouwers.forum_tools.fields.ForumToolsIDField(
                        blank=True,
                        null=True,
                        type="forum",
                        unique=True,
                        verbose_name="forum",
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="titel verslag"),
                ),
                ("brouwer", models.CharField(max_length=30)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="awards/"),
                ),
                (
                    "nomination_date",
                    models.DateField(db_index=True, default=datetime.date.today),
                ),
                ("votes", models.IntegerField(blank=True, default=0, null=True)),
                ("rejected", models.BooleanField(default=False)),
                (
                    "last_review",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="last review"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="awards.category",
                        verbose_name="categorie",
                    ),
                ),
                (
                    "last_reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="last reviewer",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nominations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    brouwers.forum_tools.fields.ForumToolsIDField(
                        blank=True,
                        null=True,
                        type="topic",
                        verbose_name="build report topic",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "votes"],
                "verbose_name": "nomination",
                "verbose_name_plural": "nominations",
                "unique_together": {("category", "topic")},
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="awards.category",
                    ),
                ),
                (
                    "project1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="awards.project",
                    ),
                ),
                (
                    "project2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="awards.project",
                    ),
                ),
                (
                    "project3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="awards.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
