# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 20:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_auto_20150405_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='last reviewer'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='project2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='awards.Project'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='project3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='awards.Project'),
        ),
    ]
