# Generated by Django 2.2.20 on 2021-04-20 20:01

from django.db import migrations, models

import autoslug.fields


class Migration(migrations.Migration):

    dependencies = [
        ("awards", "0003_auto_20160811_2230"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="name", unique=True, verbose_name="slug"
            ),
        ),
    ]
