# Generated by Django 2.2.20 on 2021-04-20 20:04

from django.db import migrations

import brouwers.forum_tools.fields


class Migration(migrations.Migration):

    dependencies = [
        ("awards", "0004_auto_20210420_2201"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="forum",
            field=brouwers.forum_tools.fields.ForumToolsIDField(
                blank=True, null=True, type="forum", unique=True, verbose_name="forum"
            ),
        ),
    ]
