# Generated by Django 2.2.20 on 2021-04-20 20:24

from django.db import migrations

import brouwers.forum_tools.fields


class Migration(migrations.Migration):

    dependencies = [
        ("awards", "0005_category_forum"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="topic",
            field=brouwers.forum_tools.fields.ForumToolsIDField(
                blank=True, null=True, type="topic", verbose_name="build report topic"
            ),
        ),
    ]
