# Generated by Django 2.2.20 on 2021-04-20 20:28
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("awards", "0006_project_topic"),
    ]

    # Removed to squash migrations
    operations = []
