# Generated by Django 2.2.20 on 2021-04-20 21:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("awards", "0007_set_topic_id_from_url"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("category", "topic")},
        ),
        migrations.RemoveField(
            model_name="project",
            name="url",
        ),
    ]
