# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0011_auto_20150729_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildphoto',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='builds.Build', verbose_name='build'),
        ),
    ]
