# Generated by Django 4.2.16 on 2024-09-26 07:30

from django.db import migrations, models

import ckeditor.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RemarkableEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="The day on which this significant event happened.",
                        verbose_name="date",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short title that should invite the user to read more.",
                        max_length=200,
                        verbose_name="title",
                    ),
                ),
                (
                    "body_text",
                    ckeditor.fields.RichTextField(
                        blank=True,
                        help_text="The full text providing more context about this specific moment.",
                        verbose_name="body text",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="An image to display on the timeline.",
                        upload_to="anniversary/20/",
                        verbose_name="image",
                    ),
                ),
            ],
            options={
                "verbose_name": "remarkable event",
                "verbose_name_plural": "remarkable events",
                "ordering": ("date",),
            },
        ),
    ]
