# Generated by Django 1.9.2 on 2016-02-26 07:52


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20150530_2311"),
    ]

    # Remove to squash migrations
    operations = []
