# Generated by Django 1.11.11 on 2018-05-07 07:20


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import brouwers.utils.storages


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20160226_0852"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataDownloadRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "finished",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="finished"
                    ),
                ),
                (
                    "zip_file",
                    models.FileField(
                        blank=True,
                        storage=brouwers.utils.storages.PrivateMediaFileSystemStorage(),
                        upload_to="",
                        verbose_name="zip file",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
