# Generated by Django 1.11.11 on 2018-05-25 20:05


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_datadownloadrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="datadownloadrequest",
            name="downloaded",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="downloaded"
            ),
        ),
    ]
