# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_customer_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=15, verbose_name="phone number"
            ),
        ),
    ]
