# Generated by Django 3.2.13 on 2022-05-04 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_auto_20200426_1617"),
        ("users", "0007_user_phone"),
    ]

    operations = []
