# Generated by Django 5.2.13 on 2026-04-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_user_ip_address_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ui_language",
            field=models.CharField(
                blank=True,
                choices=[("nl", "Dutch"), ("en", "English"), ("de", "German")],
                default="",
                help_text="Preferred UI language. If unset, your browser preferences are respected.",
                max_length=10,
                verbose_name="UI language",
            ),
        ),
    ]
