# Generated by Django 5.2.15 on 2026-06-28 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_user_ui_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "motivation",
                    models.TextField(
                        help_text="Explanation of the user why they want to create an account.",
                        verbose_name="motivation",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=None,
                        help_text="Request outcome - approved requests lead to account activation.",
                        null=True,
                        verbose_name="is approved?",
                    ),
                ),
                (
                    "approved_or_rejected_on",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="Timestamp of when the request was approved or rejected.",
                        null=True,
                        verbose_name="approved or rejected on",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
