# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 20:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumMigration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('migrated', models.NullBooleanField()),
                ('new_album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='albums.Album')),
            ],
            options={
                'ordering': ('owner', 'title'),
            },
        ),
        migrations.CreateModel(
            name='AlbumUserMigration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('django_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'album user migration',
                'verbose_name_plural': 'album user migrations',
            },
        ),
        migrations.CreateModel(
            name='PhotoMigration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(max_length=80)),
                ('filename', models.CharField(max_length=256)),
                ('pwidth', models.PositiveIntegerField(blank=True, null=True)),
                ('pheight', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('caption', models.CharField(blank=True, max_length=1024)),
                ('migrated', models.NullBooleanField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migration.AlbumMigration')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migration.AlbumUserMigration')),
            ],
            options={
                'ordering': ('album',),
            },
        ),
        migrations.CreateModel(
            name='UserMigration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('username_clean', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('hash', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'ordering': ['username_clean'],
            },
        ),
        migrations.AddField(
            model_name='albummigration',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migration.AlbumUserMigration'),
        ),
    ]
