# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brouwersdag', '0003_auto_20150603_1149'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='exhibitor',
            order_with_respect_to=None,
        ),
    ]
