# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brouwersdag', '0004_auto_20151205_2005'),
        ('brouwersdag', '0004_auto_20150722_2049'),
    ]

    operations = [
    ]
