# Generated by Django 5.2.1 on 2025-06-23 06:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("online_users", "0003_auto_20150603_1149"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TrackedUser",
        ),
    ]
