# Generated by Django 1.10 on 2016-08-16 08:11

import django.db.models.deletion
from django.db import migrations

import brouwers.kits.fields


class Migration(migrations.Migration):

    dependencies = [
        ("kitreviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kitreview",
            name="model_kit",
            field=brouwers.kits.fields.KitForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="kits.ModelKit",
                verbose_name="model kit",
            ),
        ),
    ]
