# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 08:11
from __future__ import unicode_literals

import brouwers.kits.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitreviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitreview',
            name='model_kit',
            field=brouwers.kits.fields.KitForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kits.ModelKit', verbose_name='model kit'),
        ),
    ]
