# Generated by Django 4.2.11 on 2024-06-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kitreviews", "0005_alter_kitreview_properties"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kitreview",
            name="html",
        ),
        migrations.AlterField(
            model_name="kitreview",
            name="raw_text",
            field=models.TextField(
                help_text="The content of the review. Please be detailed!",
                verbose_name="review",
            ),
        ),
    ]
