# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 18:33
from __future__ import unicode_literals

import brouwers.forum_tools.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitreviews', '0005_delete_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitReviewProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'kit review property',
                'verbose_name_plural': 'kit review properties',
            },
        ),
        migrations.CreateModel(
            name='KitReviewPropertyRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='rating')),
            ],
            options={
                'verbose_name': 'kit review property rating',
                'verbose_name_plural': 'kit review property ratings',
            },
        ),
        migrations.RemoveField(
            model_name='kitreview',
            name='negative_points',
        ),
        migrations.RemoveField(
            model_name='kitreview',
            name='positive_points',
        ),
        migrations.RemoveField(
            model_name='kitreview',
            name='rating',
        ),
        migrations.AlterField(
            model_name='kitreview',
            name='topic_id',
            field=brouwers.forum_tools.fields.ForumToolsIDField(blank=True, help_text='ID of the topic on Modelbrouwers.', null=True, type=b'topic', verbose_name='topic'),
        ),
        migrations.AlterField(
            model_name='kitreviewvote',
            name='vote',
            field=models.CharField(choices=[(b'+', b'+'), (b'-', b'-')], db_index=True, max_length=1, verbose_name='vote'),
        ),
        migrations.AddField(
            model_name='kitreviewpropertyrating',
            name='kit_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitreviews.KitReview'),
        ),
        migrations.AddField(
            model_name='kitreviewpropertyrating',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitreviews.KitReviewProperty'),
        ),
        migrations.AddField(
            model_name='kitreview',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='_kitreview_properties_+', through='kitreviews.KitReviewPropertyRating', to='kitreviews.KitReviewProperty'),
        ),
    ]
