# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 13:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitreviews', '0005_delete_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitReviewProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('rating', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='rating')),
            ],
            options={
                'verbose_name': 'kit review property',
                'verbose_name_plural': 'kit review properties',
            },
        ),
        migrations.RemoveField(
            model_name='kitreview',
            name='negative_points',
        ),
        migrations.RemoveField(
            model_name='kitreview',
            name='positive_points',
        ),
        migrations.AlterField(
            model_name='kitreview',
            name='rating',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='rating'),
        ),
        migrations.AddField(
            model_name='kitreview',
            name='prop',
            field=models.ManyToManyField(blank=True, related_name='reviews', to='kitreviews.KitReviewProperty'),
        ),
    ]
