# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitreviews', '0006_auto_20160324_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitReviewProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(b'Fitting', 'Fitting'), (b'Correctness', 'Correctness'), (b'Instructions_Clarity', 'Instructions clarity'), (b'Difficulty', 'Difficulty')], max_length=255, verbose_name='name')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='rating')),
            ],
            options={
                'verbose_name': 'kit review property',
                'verbose_name_plural': 'kit review properties',
            },
        ),
        migrations.DeleteModel(
            name='ReviewProperty',
        ),
        migrations.AlterField(
            model_name='kitreview',
            name='prop',
            field=models.ManyToManyField(blank=True, related_name='reviews', to='kitreviews.KitReviewProperty'),
        ),
    ]
