# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitreviews', '0006_auto_20160404_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitreviewproperty',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
