# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitreviews', '0009_categorie_fabrikant_kit_review_reviewer_uitbreiding'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitreview',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
