# Generated by Django 4.2.19 on 2025-04-14 21:28

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import brouwers.general.fields


class Migration(migrations.Migration):
    replaces = [
        ("general", "0001_initial"),
        ("general", "0002_auto_20180930_1917"),
        ("general", "0003_alter_userprofile_country"),
        ("general", "0004_auto_20220619_1442"),
        ("general", "0005_auto_20220619_1446"),
        ("general", "0006_auto_20221227_1158"),
        ("general", "0007_auto_20240226_0904"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("awards", "0003_auto_20160811_2230"),
        ("banning", "0004_auto_20160811_2230"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_vote", models.DateField(default=datetime.date(2010, 1, 1))),
                ("forum_nickname", models.CharField(max_length=30, unique=True)),
                (
                    "exclude_from_nomination",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, you will be excluded from Awards-nominations.",
                        verbose_name="exclude me from nominations",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="street name",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        help_text="house number (+ PO box if applicable)",
                        max_length=10,
                        verbose_name="number",
                    ),
                ),
                (
                    "postal",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="postal code"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=255, verbose_name="city"),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="province"
                    ),
                ),
                (
                    "country",
                    brouwers.general.fields.CountryField(
                        blank=True,
                        choices=[
                            ("N", "The Netherlands"),
                            ("B", "Belgium"),
                            ("D", "Germany"),
                        ],
                        max_length=1,
                        verbose_name="country",
                    ),
                ),
                (
                    "allow_sharing",
                    models.BooleanField(
                        default=False,
                        help_text="Checking this gives us permission to share your topics and albums on social media. Uncheck if you don't want to share.",
                        verbose_name="allow social sharing",
                    ),
                ),
                (
                    "categories_voted",
                    models.ManyToManyField(blank=True, to="awards.category"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["forum_nickname"],
                "verbose_name": "userprofile",
                "verbose_name_plural": "userprofiles",
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "language",
                    models.CharField(
                        choices=[("nl", "Dutch"), ("en", "English"), ("de", "German")],
                        max_length=10,
                        verbose_name="language",
                    ),
                ),
                ("from_date", models.DateTimeField(blank=True, null=True)),
                ("to_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-from_date"],
                "verbose_name": "announcement",
                "verbose_name_plural": "announcements",
            },
        ),
        migrations.CreateModel(
            name="RegistrationAttempt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True,
                        default="_not_filled_in_",
                        max_length=512,
                        verbose_name="username",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=255, verbose_name="email"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="timestamp"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        db_index=True, verbose_name="IP address"
                    ),
                ),
                ("success", models.BooleanField(default=False, verbose_name="success")),
                (
                    "type_of_visitor",
                    models.CharField(
                        default="normal user",
                        max_length=255,
                        verbose_name="type of visitor",
                    ),
                ),
                (
                    "ban",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="banning.ban",
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
                "verbose_name": "registration attempt",
                "verbose_name_plural": "registration attempts",
            },
        ),
    ]
