# Generated by Django 3.2.13 on 2022-06-19 11:33

from django.db import migrations

import brouwers.general.fields


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0002_auto_20180930_1917"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="country",
            field=brouwers.general.fields.CountryField(
                blank=True,
                choices=[
                    ("N", "The Netherlands"),
                    ("B", "Belgium"),
                    ("D", "Germany"),
                    ("F", "France"),
                ],
                max_length=1,
                null=True,
                verbose_name="country",
            ),
        ),
    ]
