# Generated by Django 3.2.13 on 2022-06-19 12:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0003_alter_userprofile_country"),
    ]

    # Removed to squash migrations
    operations = []
