# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 19:25
from __future__ import unicode_literals

from django.db import migrations


def copy_redirects(apps, schema_editor):
    OldRedirect = apps.get_model("general", "Redirect")
    NewRedirect = apps.get_model("redirects", "Redirect")

    def new_from_old(redirect):
        return NewRedirect(
            site_id=1,
            old_path='/' + redirect.path_from,
            new_path=redirect.path_to
        )

    new_redirects = [
        new_from_old(r) for r in OldRedirect.objects.all()
    ]
    NewRedirect.objects.bulk_create(new_redirects)


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20150603_1149'),
        ('redirects', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_redirects),
    ]
