# Generated by Django 3.2.13 on 2022-06-19 12:46

from django.db import migrations, models

import brouwers.general.fields


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0004_auto_20220619_1442"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="city",
            field=models.CharField(blank=True, max_length=255, verbose_name="city"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="country",
            field=brouwers.general.fields.CountryField(
                blank=True,
                choices=[
                    ("N", "The Netherlands"),
                    ("B", "Belgium"),
                    ("D", "Germany"),
                    ("F", "France"),
                ],
                max_length=1,
                verbose_name="country",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="number",
            field=models.CharField(
                blank=True,
                help_text="house number (+ PO box if applicable)",
                max_length=10,
                verbose_name="number",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="postal",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="postal code"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="province",
            field=models.CharField(blank=True, max_length=255, verbose_name="province"),
        ),
    ]
