# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20151205_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordreset',
            name='user',
        ),
        migrations.DeleteModel(
            name='PasswordReset',
        ),
    ]
