# Generated by Django 3.2.16 on 2022-12-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0005_auto_20220619_1446"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="language",
            field=models.CharField(
                choices=[("nl", "Dutch"), ("en", "English"), ("de", "German")],
                max_length=10,
                verbose_name="language",
            ),
        ),
        migrations.AlterField(
            model_name="registrationquestion",
            name="lang",
            field=models.CharField(
                choices=[("nl", "Dutch"), ("en", "English"), ("de", "German")],
                default="nl",
                max_length=10,
                verbose_name="language",
            ),
        ),
    ]
