# Generated by Django 5.2.1 on 2025-06-23 06:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0001_initial_squashed_0007_auto_20240226_0904"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="allow_sharing",
        ),
    ]
