# Generated by Django 1.10 on 2016-08-11 20:30


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import autoslug.fields

import brouwers.forum_tools.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forum_tools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupBuild",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "forum",
                    brouwers.forum_tools.fields.ForumToolsIDField(
                        blank=True,
                        help_text="Forum id of the group build subforum",
                        null=True,
                        type="forum",
                        verbose_name="forum id",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        help_text="Theme/name of the group build",
                        max_length=100,
                        verbose_name="theme",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=True,
                        populate_from="theme",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Short description", verbose_name="description"
                    ),
                ),
                (
                    "start",
                    models.DateField(
                        blank=True,
                        help_text="Date when you want to start building.",
                        null=True,
                        verbose_name="start date",
                    ),
                ),
                (
                    "end",
                    models.DateField(
                        blank=True,
                        help_text="Date this build ends.",
                        null=True,
                        verbose_name="end date",
                    ),
                ),
                (
                    "duration",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (30, "30 days"),
                            (61, "2 months"),
                            (92, "3 months"),
                            (183, "6 months"),
                            (365, "one year"),
                        ],
                        default=92,
                        verbose_name="duration",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("concept", "concept/idea"),
                            ("submitted", "submitted for review"),
                            ("accepted", "accepted"),
                            ("denied", "denied"),
                            ("extended", "extended"),
                        ],
                        default="concept",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "users_can_vote",
                    models.BooleanField(
                        default=False,
                        help_text="Let users vote to determine the build popularity",
                        verbose_name="users can vote",
                    ),
                ),
                (
                    "upvotes",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="upvotes"
                    ),
                ),
                (
                    "downvotes",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="downvotes"
                    ),
                ),
                ("rules", models.TextField(blank=True)),
                (
                    "rules_topic",
                    brouwers.forum_tools.fields.ForumToolsIDField(
                        blank=True, null=True, type="topic", verbose_name="rules topic"
                    ),
                ),
                (
                    "homepage_topic",
                    brouwers.forum_tools.fields.ForumToolsIDField(
                        blank=True,
                        null=True,
                        type="topic",
                        verbose_name="topic to direct to from calendar",
                    ),
                ),
                (
                    "introduction_topic",
                    brouwers.forum_tools.fields.ForumToolsIDField(
                        blank=True,
                        null=True,
                        type="topic",
                        verbose_name="introduction topic",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("reason_denied", models.TextField(blank=True)),
                (
                    "admins",
                    models.ManyToManyField(
                        help_text="Users who manage the group build.",
                        related_name="admin_groupbuilds",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="admins",
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groupbuilds_applied",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forum_tools.ForumCategory",
                        verbose_name="forum category",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified", "-created"),
                "verbose_name": "group build",
                "verbose_name_plural": "group builds",
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="model name"
                    ),
                ),
                (
                    "finished",
                    models.BooleanField(default=False, verbose_name="finished"),
                ),
                (
                    "topic",
                    brouwers.forum_tools.fields.ForumToolsIDField(
                        blank=True, null=True, type="topic", verbose_name="topic"
                    ),
                ),
                (
                    "points",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="points"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "groupbuild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="groupbuilds.GroupBuild",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gb_participants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "group build participant",
                "verbose_name_plural": "group build participants",
            },
        ),
        migrations.AddField(
            model_name="groupbuild",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="groupbuilds",
                through="groupbuilds.Participant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
