# Generated by Django 2.0.13 on 2020-04-26 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groupbuilds", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupbuild",
            name="admins",
            field=models.ManyToManyField(
                help_text="Users who manage the group build.",
                limit_choices_to={"is_active": True},
                related_name="admin_groupbuilds",
                to=settings.AUTH_USER_MODEL,
                verbose_name="admins",
            ),
        ),
    ]
