# Generated by Django 4.2.10 on 2024-03-04 21:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groupbuilds", "0002_auto_20200426_1617"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupbuild",
            name="admins",
        ),
        migrations.RemoveField(
            model_name="groupbuild",
            name="downvotes",
        ),
        migrations.RemoveField(
            model_name="groupbuild",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="groupbuild",
            name="upvotes",
        ),
        migrations.RemoveField(
            model_name="groupbuild",
            name="users_can_vote",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="points",
        ),
    ]
