# Generated by Django 5.2.1 on 2025-06-23 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum_tools", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forumlinksynced",
            name="base",
        ),
        migrations.DeleteModel(
            name="ForumLinkBase",
        ),
        migrations.DeleteModel(
            name="ForumLinkSynced",
        ),
    ]
