# Generated by Django 1.10 on 2016-08-11 20:30


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import autoslug.fields
import djchoices.choices

import brouwers.kits.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        error_messages={"unique": "This brand already exists"},
                        max_length=100,
                        unique=True,
                        verbose_name="brand",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from="name",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, upload_to="images/brand_logos/", verbose_name="logo"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether the brand still exists or not",
                        verbose_name="is active",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "verbose_name": "brand",
                "verbose_name_plural": "brands",
            },
        ),
        migrations.CreateModel(
            name="ModelKit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="kit name"
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from=brouwers.kits.models.get_kit_slug,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "kit_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Kit number as found on the box.",
                        max_length=50,
                        verbose_name="kit number",
                    ),
                ),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (10, "very easy"),
                            (20, "easy"),
                            (30, "medium"),
                            (40, "hard"),
                            (50, "very hard"),
                        ],
                        default=30,
                        validators=[
                            djchoices.choices.ChoicesValidator(
                                {
                                    10: "very easy",
                                    20: "easy",
                                    30: "medium",
                                    40: "hard",
                                    50: "very hard",
                                }
                            )
                        ],
                        verbose_name="difficulty",
                    ),
                ),
                (
                    "box_image",
                    models.ImageField(
                        blank=True,
                        upload_to="kits/box_images/%Y/%m",
                        verbose_name="box image",
                    ),
                ),
                ("submitted_on", models.DateTimeField(auto_now_add=True)),
                ("is_reviewed", models.BooleanField(default=False)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="kits.Brand",
                        verbose_name="brand",
                    ),
                ),
                (
                    "duplicates",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Kits that are the same but have another producer.",
                        related_name="_modelkit_duplicates_+",
                        to="kits.ModelKit",
                        verbose_name="duplicates",
                    ),
                ),
            ],
            options={
                "verbose_name": "model kit",
                "verbose_name_plural": "model kits",
            },
        ),
        migrations.CreateModel(
            name="Scale",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scale",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        error_messages={"unique": "This scale already exists"},
                        unique=True,
                        verbose_name="scale",
                    ),
                ),
            ],
            options={
                "ordering": ["scale"],
                "verbose_name": "scale",
                "verbose_name_plural": "scales",
            },
        ),
        migrations.AddField(
            model_name="modelkit",
            name="scale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="kits.Scale",
                verbose_name="scale",
            ),
        ),
        migrations.AddField(
            model_name="modelkit",
            name="submitter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
