# Generated by Django 4.2.10 on 2024-03-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kits", "0002_boxart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelkit",
            name="duplicates",
            field=models.ManyToManyField(
                blank=True,
                help_text="Kits that are the same but have another producer.",
                to="kits.modelkit",
                verbose_name="duplicates",
            ),
        ),
    ]
