# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 13:25
from __future__ import unicode_literals

import autoslug.fields
import brouwers.kits.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0004_auto_20150914_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from=b'name', unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='modelkit',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from=brouwers.kits.models.get_kit_slug, unique=True, verbose_name='slug'),
        ),
    ]
