# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 17:09
from __future__ import unicode_literals

import autoslug.fields
import brouwers.kits.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0005_auto_20160306_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelkit',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=b'name', unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='modelkit',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=brouwers.kits.models.get_kit_slug, unique=True, verbose_name='slug'),
        ),
    ]
